name: Create build for release


on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Set up npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Setup Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install

      - name: Build and Convert the release macOS version
        run: |
          npm run build
          xcrun safari-web-extension-converter dist
          xcodebuild -project ./Prettier\ Lichess/Prettier\ Lichess.xcodeproj -target "Prettier Lichess (macOS)"
          zip -r ./prettierlichess-safari.zip /Users/runner/work/prettierlichess/prettierlichess/Prettier\ Lichess/build/Release/Prettier\ Lichess.app

      - name: Upload build version as artifact
        uses: actions/upload-artifact@v3
        with:
          name: prettierlichess-safari
          path: ./prettierlichess-safari.zip
          

  upload:
    name: Upload build to github release
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download source code
        uses: actions/download-artifact@v3
        with:
          name: prettierlichess-safari
          path: ./prettierlichess-safari.zip

      - name: Upload build to release
        uses: svenstaro/upload-release-action@cc92c9093e5f785e23a3d654fe2671640b851b5f
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./prettierlichess-safari.zip
          tag: ${{ github.ref }}
          overwrite: true
          
